EcomVue/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.login');
});

Auth::routes();


Route::group(array('prefix' => 'dashboard','as'=>'admin.', 'middleware' => 'auth'), function() {

    Route::resource('/admin', 'Admin\AdminController');
    Route::resource('/product', 'Admin\ProductController');

});

EcomVue/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
    protected $fillable=[
        'name',
        'price',
        'quantity',
        'image',
        'user_id',
    ];
}

EcomVue/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

EcomVue/app/Http/Controllers/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Hash;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.admin.index')->with('users',User::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.admin.add');
    }

    public function show ($id){

       return "عرض";

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[

            'name'=>'required|string|',
            'email'=>'required||string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);
        $inputs=$request->all();
        $inputs['password']=Hash::make($request->password);

        User::create($inputs);
        alert()->success('تم اضافة الادمن بنجاح !')->autoclose(5000);
        return back();

    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, $id)
    {
        $user=User::find($id);


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }
}

EcomVue/app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Product;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Hash;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.products.index')->with('items',Product::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.products.add');
    }

    public function show ($id){

       return "عرض";

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[

            'name'=>'required|string|',
            'price'=>'required|string|numeric',
            'image'=>'required|image|',
            'quantity' => 'required|string|',
        ]);
        $image = uploader($request,'image');
        $inputs=$request->all();
        $inputs['image']=$image;
        $inputs['user_id']=auth()->id();
        Product::create($inputs);
        alert()->success('تم اضافة المنتج بنجاح !')->autoclose(5000);
        return back();
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, $id)
    {
        $product=Product::find($id);


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }
}

EcomVue/app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Product;
use App\Http\Traits\ApiResponses;
use App\Http\Controllers\Controller;



class ProductController extends Controller
{
    use ApiResponses;

    /**
     *
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate($this->paginateNumber);
        $products = new \App\Http\Resources\Product($products);
        return $this->apiResponse($products);
    }

}

EcomVue/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

EcomVue/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

EcomVue/resources/views/admin/admin/add.blade.php
@extends('admin.layout')
@section('title')
اضافة أدمن جديد
@endsection

@section('header')

@endsection

@section('content')
    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">اضافة أدمن جديد</h5>
                    <div class="heading-elements">
                        <ul class="icons-list">

                            <li><a data-action="reload"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="panel-body">
                    {!!Form::open( ['route' => 'admin.admin.store' ,'class'=>'form phone_validate', 'method' => 'Post','files' => true]) !!}
                    @include('admin.admin.form')
                    {!!Form::close() !!}
                </div>
            </div>
        </div>
    </div>
<!-- #END# Basic Validation -->
@endsection

@section('script')
    <script type="text/javascript" src="{{asset('admin/assets/js/pages/form_layouts.js')}}"></script>
@endsection

EcomVue/resources/views/admin/admin/edit.blade.php
@extends('admin.layout')
@section('title')
    تعديل
    {{ $user->name }}
@endsection

@section('header')

@endsection

@section('content')
    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">تعديل {{$user->name}}</h5>
                    <div class="heading-elements">
                        <ul class="icons-list">

                            <li><a data-action="reload"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="panel-body">
                            {!!Form::model($user , ['route' => ['admin.admin.update' , $user->id] ,'class'=>'phone_validate','method' => 'PATCH','files'=>true]) !!}
                            @include('admin.admin.form')
                            {!!Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script type="text/javascript" src="{{asset('admin/assets/js/pages/form_layouts.js')}}"></script>

@endsection

EcomVue/resources/views/admin/admin/form.blade.php
@if (count($errors) > 0)
<div class="alert alert-danger">
  <ul>
    @foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif


<div class="form-group col-md-12 pull-left">
    <label>الاسم  </label>  <span class="label bg-danger help-inline">مطلوب</span>
    {!! Form::text("name",null,['class'=>'form-control','placeholder'=>'  الاسم  '])!!}
</div>


<div class="form-group col-md-6 pull-left">
    <label> الإيميل </label>   <span class="label bg-danger help-inline">مطلوب</span>
    {!! Form::email("email",null,['class'=>'form-control','placeholder'=>'أكتب هنا  الايميل'])!!}
</div>

<div class="form-group col-md-6 pull-left">
    <label>باسورد </label>   <span class="label bg-danger help-inline">مطلوب</span>
    <input type="password" class="form-control" name="password" placeholder="اكتب هنا الباسورد">
</div>

<div class="form-group col-md-6 pull-left">
    <label>   إعادة كتابة الباسورد </label> <span class="label bg-danger help-inline">مطلوب</span>
    <input type="password" class="form-control" name="password_confirmation" placeholder="أعد هنا كتابة الباسورد">
</div>





<div class="text-center col-md-12">
    <div class="text-right">
        <button type="submit" class="btn btn-success">حفظ <i class="icon-arrow-left13 position-right"></i></button>
    </div>
</div>

@push('scripts')

@endpush

EcomVue/resources/views/admin/admin/index.blade.php
@extends('admin.layout')
@section('title')
  أعضاء الاداره
@endsection

@section('header')

@endsection
@section('content')

    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">كل أعضاء الاداره</h5>
            <div class="heading-elements">
                <ul class="icons-list">

                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
            عرض كل أعضاء الاداره والتحكم بهم وبكل العمليات الخاصة بهم مع امكانية البحث وتصدير تقارير وملفات وطباعتهم
        </div>

        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th> # </th>
                <th> الإسم  </th>
                <th> الايميل </th>
                <th> حاله العضوية </th>
                <th> العمليات </th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $key=>$admin)
                <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$admin->name}}</td>
                    <td>{{$admin->email}}</td>
                    <td>
                        <span class="label label-info">مدير الموقع</span>
                    </td>
                    {!!Form::open( ['route' => ['admin.admin.destroy',$admin->id] ,'id'=>'delete-form'.$admin->id, 'method' => 'Delete']) !!}
                    {!!Form::close() !!}
                    <td>
                        <a href="{{route('admin.admin.edit',['id'=>$admin->id])}}" data-toggle="tooltip" data-original-title="تعديل"> <i class="icon-pencil7 text-inverse" style="margin-left: 10px"></i> </a>
                        <a href="#" onclick="Delete({{$admin->id}})" data-toggle="tooltip" data-original-title="حذف"> <i class="icon-trash text-inverse text-danger" style="margin-left: 10px"></i> </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->




    <script>
        function Delete(id) {
            var item_id=id;
            console.log(item_id);
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف هذا المدير ؟",
                icon: "warning",
                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function(isConfirm){
                if(isConfirm){
                    document.getElementById('delete-form'+item_id).submit();
                }
                else{
                    swal("تم االإلفاء", "حذف المدير تم الغاؤه",'info',{buttons:'موافق'});
                }
            });
        }
    </script>


@endsection
@section('script')
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/tables/datatables/datatables.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/tables/datatables/extensions/buttons.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/selects/select2.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/pages/datatables_extension_buttons_init.js')}}"></script>
@endsection

EcomVue/resources/views/admin/breadcrumb.blade.php
<!-- Page header -->
<div class="page-header page-header-default">
    <div class="page-header-content">
        <div class="page-title">
            <h4><a href="{{Session::get('_previous')['url']}}" ><i class="icon-arrow-right6 position-left"></i></a> <span class="text-semibold">لوحة تحكم موقع تطبيق منتجات </span> - @yield('title')</h4>
        </div>

        <div class="heading-elements">
            <div class="heading-btn-group">
                <a href="{{asset('dashboard')}}" class="btn btn-link btn-float has-text"><i class="icon-bars-alt text-primary"></i><span>بعض الاحصائيات</span></a>
                <a href="{{asset('dashboard/admin')}}" class="btn btn-link btn-float has-text"><i class="icon-users text-primary"></i> <span>أعضاء الاداره</span></a>
            </div>
        </div>
    </div>

    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="{{asset('dashboard')}}"><i class="icon-home2 position-left"></i> لوحة التحكم</a></li>
            <li class="active">@yield('title')</li>
        </ul>
    </div>
</div>
<!-- /page header -->

EcomVue/resources/views/admin/city_map.blade.php
<div id="dir" >
    <div id="map" class="border-bottom" style="height: 500px;width: 100%"></div>
</div>

@section('script')
    {!! Html::script('https://maps.googleapis.com/maps/api/js?key=AIzaSyCsT140mx0UuES7ZwcfY28HuTUrTnDhxww&libraries=places&language=ar') !!}
    <script >
        function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: 24.7128688, lng: 46.8126935},
                zoom: 9
            });

            if ($('#bounders').val()=='') {

                var bounds = [
                    {lat: 24.943944934407117, lng: 46.23451969062501},
                    {lat: 24.51485745266444, lng: 46.23451969062501},
                    {lat: 24.51485745266444, lng: 47.26998111640626},
                    {lat: 24.943944934407117, lng: 47.26998111640626}
                ];
            }else{
                var  bounds=JSON.parse($('#bounders').val());
                map.setCenter({
                    lat:bounds[0].lat,
                    lng:bounds[0].lng
                });
                map.setZoom(11);

            }

            // Construct the polygon.
            var color;
            if($('#color').val()==''){
                color='#ff0020';
            }else{
                color=$('#color').val();
            }
      /*      var Rectangle = new google.maps.Rectangle({
                bounds: bounds,
                fillColor:color,
                editable: true,
                draggable: true,
            });
            $('#color').change(function () {
               Rectangle.setOptions({fillColor:$('#color').val()});
            });
            Rectangle.setMap(map);

            Rectangle.addListener('bounds_changed',function () {
                console.log(Rectangle.getBounds().toJSON());
                $('#bounders').val(JSON.stringify(Rectangle.getBounds().toJSON()));
            });*/
            var marker = new google.maps.Marker({
                position: {lat:bounds[0].lat,lng:bounds[0].lng},
                map: map,
                draggable: true,
            });
            google.maps.event.addListener(marker, 'dragend', function(e) {
                $('#marker').val(JSON.stringify(marker.getPosition()));
            });
            var polygon = new google.maps.Polygon({
                paths: bounds,
                strokeColor: color,
                strokeOpacity: 0.8,
                strokeWeight: 2,
                fillColor: color,
                fillOpacity: 0.35,
                editable: true,
                draggable: true,

            });
            $('#color').change(function () {
                polygon.setOptions({fillColor:$('#color').val(),strokeColor:$('#color').val()});
            });
            polygon.setMap(map);
            polygon.getPaths().forEach(function(path, index) {
                google.maps.event.addListener(path, 'insert_at', function(){
                    console.log('insert');
                    console.log(pathToJSON(polygon.getPath().getArray()));
                });

                google.maps.event.addListener(path, 'remove_at', function(){
                    console.log('remove');
                    console.log(pathToJSON(polygon.getPath().getArray()));
                });

                google.maps.event.addListener(path, 'set_at', function(){
                    console.log('modified');
                    console.log(pathToJSON(polygon.getPath().getArray()));
                });
            });
            google.maps.event.addListener(polygon, 'dragend', function(){
                console.log('drag polygon');
                console.log(pathToJSON(polygon.getPath().getArray()));
            });




            /*  polygon.addListener('bounds_changed',function () {
              path=[];
              polygon.getPath().getArray().forEach(function (i) {
                  path.push({lat:i.lat(),lng:i.lng()});
              });
              $('#bounders').val(JSON.stringify(path));
              console.log(JSON.stringify(path));
          });*/



        }
        function pathToJSON(points){
            var path=[];
        points.forEach(function (i) {
                path.push({lat:i.lat(),lng:i.lng()});
            });
        path=JSON.stringify(path);
        $('#bounders').val(path);
        return path;
        }

        google.maps.event.addDomListener(window, 'load', initMap);
    </script>
@endsection

EcomVue/resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>تسجيل الدخول</title>

    <!-- Global stylesheets -->
    <link href="https://fonts.googleapis.com/css?family=Cairo" rel="stylesheet">
    <link href="{{asset('admin/assets/css/icons/icomoon/styles.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/assets/css/bootstrap.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/assets/css/core.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/assets/css/components.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('admin/assets/css/colors.css')}}" rel="stylesheet" type="text/css">
    <!-- /global stylesheets -->

    <!-- Core JS files -->
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/loaders/pace.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/core/libraries/jquery.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/core/libraries/bootstrap.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/loaders/blockui.min.js')}}"></script>
    <!-- /core JS files -->

    <!-- Theme JS files -->
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/styling/uniform.min.js')}}"></script>

    <script type="text/javascript" src="{{asset('admin/assets/js/core/app.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/pages/login.js')}}"></script>
    <!-- /theme JS files -->

</head>

<body class="login-container" style="background-image: linear-gradient(#1d58e2, #1d68a7);  ;margin-bottom: 30px;">

<!-- Page container -->
<div class="page-container">

    <!-- Page content -->
    <div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Content area -->
            <div class="content">

                @if(session()->has('status'))
                <div class="alert alert-danger">
                    <center>{{session()->get('status')}}</center>
                </div>
                @endif

                <!-- Advanced login -->
                <form method="POST" action="{{ route('login') }}">
                    {!! csrf_field() !!}
                    <div class="panel panel-body login-form">
                        <div class="text-center">

                            <h5 class="content-group-lg">تسجيل الدخول <small class="display-block">ادخل بياناتك</small></h5>
                        </div>

                        <div class="form-group has-feedback has-feedback-left">
                            <input id="email" oninvalid="this.setCustomValidity('من فضلك قم بادخال الايميل بشكل صحيح')" type="email" placeholder="اكتب الايميل" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required autofocus>
                            <div class="form-control-feedback">
                                <i class="icon-user text-muted"></i>
                            </div>
                            @if ($errors->has('email'))
                                <span class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                            @endif
                        </div>

                        <div class="form-group has-feedback has-feedback-left">

                            <input id="password" type="password" placeholder="اكتب الباسورد" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                            @if ($errors->has('password'))
                                <span class="invalid-feedback">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                            @endif
                            <div class="form-control-feedback">
                                <i class="icon-lock2 text-muted"></i>
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn bg-blue btn-block" style="background-image: linear-gradient(#1d58e2, #1d68a7);border-color: rgb(191, 145, 59)">تسجيل دخول <i class="icon-circle-left2 position-right"></i></button>
                        </div>
                    </div>
                </form>
                <!-- /advanced login -->

            </div>
            <!-- /content area -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</div>
<!-- /page container -->

</body>
</html>

EcomVue/resources/views/admin/nav.blade.php
<!-- Main sidebar -->
<div class="sidebar sidebar-main ">
    <div class="sidebar-content">

        <!-- User menu -->
        <div class="sidebar-user">
            <div class="category-content">
                <div class="media">
                    <a href="#" class="media-left">
                        <img src="" class="img-circle img-sm" alt="">
                    </a>

                    <div class="media-body">
                        <span class="media-heading text-semibold">{{Auth::user()->name}}</span>
                        <div class="text-size-mini text-muted">
                            <i class="icon-pin text-size-small"></i> مدير الموقع
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- /user menu -->

        <!-- Main navigation -->
        <div class="sidebar-category sidebar-category-visible">
            <div class="category-content no-padding">


                <ul class="navigation navigation-main navigation-accordion">


                    <!-- Main -->
                    <li class="navigation-header"><span>الاعدادات الرئيسية</span> <i class="icon-menu"
                    title="Main pages"></i></li>





                    <li class="navigation-header"><span>المستخدمين  </span> <i class="icon-menu" title="Main pages"></i></li>

                    <li>
                        <a href="#"><i class="icon-megaphone"></i> <span>المستخدمين</span></a>
                        <ul>
                            <li class="{{ (Request::is('dashboard/admin') ? 'active' : '')}}"><a
                                        href="{{route('admin.admin.index')}}"><i class="icon-list"></i> كل  المستخدمين </a>
                            </li>
                            <li class="{{  (Request::is('dashboard/admin/create') ? 'active' : '')}}"><a
                                        href="{{route('admin.admin.create')}}"><i class="icon-megaphone"></i> اضافة مستخدم جديد</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="icon-megaphone"></i> <span>المنتجات</span></a>
                        <ul>
                            <li class="{{ (Request::is('dashboard/product') ? 'active' : '')}}"><a
                                        href="{{route('admin.product.index')}}"><i class="icon-list"></i> كل  المنتجات </a>
                            </li>
                            <li class="{{  (Request::is('dashboard/product/create') ? 'active' : '')}}"><a
                                        href="{{route('admin.product.create')}}"><i class="icon-megaphone"></i> اضافة منتج جديد</a></li>
                        </ul>
                    </li>


         

                </ul>
            </div>
        </div>
        <!-- /main navigation -->

    </div>
</div>
<!-- /main sidebar -->

EcomVue/resources/views/admin/products/index.blade.php
@extends('admin.layout')
@section('title')
  أعضاء المنتجات
@endsection

@section('header')

@endsection
@section('content')

    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">كل  المنتجات </h5>
            <div class="heading-elements">
                <ul class="icons-list">

                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
            عرض كل المنتجات الاداره والتحكم بهم وبكل العمليات الخاصة بهم مع امكانية البحث وتصدير تقارير وملفات وطباعتهم
        </div>

        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th> # </th>
                <th> الإسم  </th>
                <th> السعر </th>
                <th> الكمية   </th>
                <th> الصورة   </th>
                <th> العمليات </th>
            </tr>
            </thead>
            <tbody>
            @foreach($items as $key=>$item)
                <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$item->name}}</td>
                    <td>{{$item->price}}</td>
                    <td><img src="{{getimg($item->image)}}" width="100px"></td>
                    <td>
                        <span class="label label-info">{{$item->quantity}}  </span>
                    </td>
                    {!!Form::open( ['route' => ['admin.product.destroy',$item->id] ,'id'=>'delete-form'.$item->id, 'method' => 'Delete']) !!}
                    {!!Form::close() !!}
                    <td>
                        <a href="{{route('admin.product.edit',['id'=>$item->id])}}" data-toggle="tooltip" data-original-title="تعديل"> <i class="icon-pencil7 text-inverse" style="margin-left: 10px"></i> </a>
                        <a href="#" onclick="Delete({{$item->id}})" data-toggle="tooltip" data-original-title="حذف"> <i class="icon-trash text-inverse text-danger" style="margin-left: 10px"></i> </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->




    <script>
        function Delete(id) {
            var item_id=id;
            console.log(item_id);
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف هذا المدير ؟",
                icon: "warning",
                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function(isConfirm){
                if(isConfirm){
                    document.getElementById('delete-form'+item_id).submit();
                }
                else{
                    swal("تم االإلفاء", "حذف المدير تم الغاؤه",'info',{buttons:'موافق'});
                }
            });
        }
    </script>


@endsection
@section('script')
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/tables/datatables/datatables.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/tables/datatables/extensions/buttons.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/plugins/forms/selects/select2.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('admin/assets/js/pages/datatables_extension_buttons_init.js')}}"></script>
@endsection